### ISSUE TITLE
error add listng

### ISSUE THREAD

**Issue by falitroke** [acseo/docker-cocorico#5]
when I try add listing in the last step, error Fatal error: Uncaught exception 'Swift_TransportException' with message 'Connection could not be established with host 127.0.0.1 [Connection refused #111]' in /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:265 Stack trace: #0 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(62): Swift_Transport_StreamBuffer->_establishSocketConnection() #1 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(113): Swift_Transport_StreamBuffer->initialize(Array) #2 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/MemorySpool.php(74): Swift_Transport_AbstractSmtpTransport->start() #3 /var/www/html/vendor/symfony/symfony/src/Symfony/Bridge/Monolog/Handler/SwiftMailerHandler.php(88): Swift_MemorySpool->flushQueue(Object(Swift_Transport_EsmtpTransport)) #4 /var/www/html/vendor/symfony/symfony/src/Symfony/Bridge/Monolog/Handler/SwiftMailerHandler.php(65): Symfony\Bridge\Monolog\Handler\SwiftMailerHandle in /var/www/html/app/bootstrap.php.cache on line 3183

I think is a problem with smtp server...

**Comment by npotier** [comment]
Hi @falitroke I think that you should check your SMTP configuration in file ```app/config/parameters.yml```

**Comment by falitroke** [comment]
Yes I fix this.
 php5_imagick  also does not  installed when deploying the docker, to fix ,  docker exec -i -t cocorico-web apt-get update 
docker exec -i -t cocorico-web apt-get install php5_imagick 
and the images in de app is solved.

Thanks @npotier  for this project
